version: '3.1'
services:
  activemqsim_dev:
    image: webcenter/activemq:5.14.3
    ports:
      - "61619:61616"
      - "8169:8161"
    environment:
      - ACTIVEMQ_STATIC_QUEUES=simReq;dataReq;dbReq;simJob;workerEvent
      - ACTIVEMQ_STATIC_TOPICS=clientStatus;serviceControl
      - ACTIVEMQ_MIN_MEMORY=512
      - ACTIVEMQ_MAX_MEMORY=2048
      - ACTIVEMQ_ENABLED_SCHEDULER=true
      - ACTIVEMQ_USERS_clientUser=dummy
      - ACTIVEMQ_GROUPS_reads=clientUser
      - ACTIVEMQ_GROUPS_writes=clientUser
      - ACTIVEMQ_CONFIG_AUTHENABLED=false
    networks:
      - vcellnet
    deploy:
      mode: replicated
      replicas: 1

networks:
  vcellnet:
secrets:
  jmspswd:
    file: ${VCELL_SECRETS_DIR}/jmspswd.txt
